# Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImVtYWlsIjoiU3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJHdWVzdCIsImlhdCI6MTY4NDczODUyOCwiZXhwIjoxNjg0NzQyMTI4fQ.0YipASPbLnCeu929vSQQrdd_wHpWJv682AD4GUqaUIU

# # REGISTER: Standard check
# POST http://127.0.0.1:6001/register HTTP/1.1
# content-type: application/json

# {
#     "username":"Superuser",
#     "email":"Superuser@gmail.com",
#     "password":"Superuser"
# }

# # REGISTER: All fields included check
# POST http://127.0.0.1:6001/register HTTP/1.1
# content-type: application/json

# {
#     "email":"user1@gmail.com",
#     "password":"user1"
# }

# # LOGIN: Standard check
# POST http://127.0.0.1:6001/login HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwicm9sZSI6Ikd1ZXN0IiwiaWF0IjoxNjg0NzM4MjM2LCJleHAiOjE2ODQ3NDE4MzZ9.mOFu5L6Ui_0-Hc2Qu0qhA1FX7a2Bw352pocKCpO0yq0

# {
#     "username":"Superuser",
#     "email":"sudoUser@gmail.com",
#     "password": "Superuser"
# }

# # LOGIN: All fields included check
# POST http://127.0.0.1:6001/login HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWF0IjoxNjg0NzM4Mjc0LCJleHAiOjE2ODQ3NDE4NzR9.1UNrxnkjhdcYnNXvWeniqD-joQThqQq9f833E_5OPvg

# {
#     "email":"user1@gmail.com",
#     "password":"user1"
# }

# # LOGIN: Auth check
# POST http://127.0.0.1:6001/login HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiaWF0IjoxNjg0NzM4Mjc0LCJleHAiOjE2ODQ3NDE4NzR9.1UNrxnkjhdcYnNXvWeniqD-joQThqQq9f833E_5OPvg

# {
#     "username":"jatin",
#     "email":"user1@gmail.com",
#     "password":"user"
# }

# # SEARCH: Standard check
# GET http://127.0.0.1:6001/crud HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImVtYWlsIjoiU3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJHdWVzdCIsImlhdCI6MTY4NDczODUyOCwiZXhwIjoxNjg0NzQyMTI4fQ.0YipASPbLnCeu929vSQQrdd_wHpWJv682AD4GUqaUIU

# {
#     "email":"user1@gmail.com",
#     "password":"user1"
# }

# # SEARCH: All fields check
# GET http://127.0.0.1:6001/crud HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImVtYWlsIjoiU3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJHdWVzdCIsImlhdCI6MTY4NDczODUyOCwiZXhwIjoxNjg0NzQyMTI4fQ.0YipASPbLnCeu929vSQQrdd_wHpWJv682AD4GUqaUIU

# {
#     "password":"user1"
# }

# # SEARCH: Auth check
# GET http://127.0.0.1:6001/crud HTTP/1.1
# content-type: application/json

# {
#     "email":"user1@gmail.com",
#     "password":"user"
# }

# # UPDATE: Standard check
# PATCH http://127.0.0.1:6001/crud HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImVtYWlsIjoiU3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJHdWVzdCIsImlhdCI6MTY4NDczODUyOCwiZXhwIjoxNjg0NzQyMTI4fQ.0YipASPbLnCeu929vSQQrdd_wHpWJv682AD4GUqaUIU

# {
#     "email":"Superuser@gmail.com",
#     "password":"Superuser",
#     "newName":"Superuser",
#     "newEmail":"sudoUser@gmail.com",
#     "newRole":"CTO"
# }

# # UPDATE: All fields check
# PATCH http://127.0.0.1:6001/crud HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImVtYWlsIjoiU3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJHdWVzdCIsImlhdCI6MTY4NDczODUyOCwiZXhwIjoxNjg0NzQyMTI4fQ.0YipASPbLnCeu929vSQQrdd_wHpWJv682AD4GUqaUIU

# {
    
#     "password":"user1",
#     "newName":"userNameChange",
#     "newEmail":"user@gmail.com",
#     "newRole":"Coder"
# }

# # UPDATE: Auth check
# PATCH http://127.0.0.1:6001/crud HTTP/1.1
# content-type: application/json

# {
#     "email":"user@gmail.com",
#     "password":"user"
# }

# # DELETE: All fields check
# DELETE http://127.0.0.1:6001/crud HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImVtYWlsIjoiU3VwZXJ1c2VyQGdtYWlsLmNvbSIsInJvbGUiOiJHdWVzdCIsImlhdCI6MTY4NDczODUyOCwiZXhwIjoxNjg0NzQyMTI4fQ.0YipASPbLnCeu929vSQQrdd_wHpWJv682AD4GUqaUIU

# {
#     "password":"user1"
# }

# # DELETE: Auth check
# DELETE http://127.0.0.1:6001/crud HTTP/1.1
# content-type: application/json

# {
#     "email":"user@gmail.com",
#     "password":"user1"
# }

# DELETE: Standard check
DELETE http://127.0.0.1:6001/crud HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImVtYWlsIjoic3Vkb1VzZXJAZ21haWwuY29tIiwiaWF0IjoxNjg0NzM5MTk0LCJleHAiOjE2ODQ3NDI3OTR9.0ItIkXwi_rEcTI6cXFmV8LtBT7N0cEE5krdzBckk8qo

{
    "email":"sudoUser@gmail.com",
    "password":"Superuser"
}